version: "3.8"

services:
  prep:
    env_file:
      - disk.env

  hub:
    env_file:
      - disk.env

  admin:
    env_file:
      - disk.env

  reader:
    env_file:
      - disk.env

  nginx:
    env_file:
      - disk.env
