version: "3.8"

services:
  hub:
    image: ${HUB_IMAGE}
    restart: always
    env_file:
      - .env
    volumes:
      - "./configs/gaia/hub-config.json:/src/hub/etc/config.json"
      - "${LOCAL_DISK}:${GAIA_DISK_STORAGE_ROOT_DIR}"
    ports:
      - 3000:3000
    environment:
      CONFIG_PATH: "/src/hub/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: ${GAIA_DISK_STORAGE_ROOT_DIR}
    networks:
      - gaia

  admin:
    image: ${ADMIN_IMAGE}
    restart: always
    env_file:
      - .env
    volumes:
      - "./configs/gaia/admin-config.json:/src/admin/etc/config.json"
      - "./configs/gaia/hub-config.json:/tmp/hub/config.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8009:8009
    environment:
      CONFIG_PATH: "/src/admin/etc/config.json"
    networks:
      - gaia
    command: node lib/index.js

  reader:
    image: ${READER_IMAGE}
    restart: always
    env_file:
      - .env
    volumes:
      - "./configs/gaia/reader-config.json:/src/reader/etc/config.json"
      - "${LOCAL_DISK}:${GAIA_DISK_STORAGE_ROOT_DIR}"
    ports:
      - 8008:8008
    environment:
      CONFIG_PATH: "/src/reader/etc/config.json"
      GAIA_DISK_STORAGE_ROOT_DIR: "${GAIA_DISK_STORAGE_ROOT_DIR}"
    networks:
      - gaia

  nginx:
    image: ${NGINX_IMAGE}
    restart: always
    env_file:
      - .env
    volumes:
      - nginx_ssl:/etc/letsencrypt
      - ./configs/nginx/user_conf.d:/etc/nginx/user_conf.d
      # - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      # - "./nginx/conf.d:/etc/nginx/conf.d"
      # - "./nginx/certbot/conf:/etc/letsencrypt"
      # - "./nginx/html/index.html:/usr/share/nginx/html/index.html"
    ports:
      - 80:80
      - 443:443
    # environment:
    #   SERVER_NAME: "${DOMAIN}"
    #   SERVER_HTTP_PORT: "80"
    networks:
      - gaia
    depends_on:
      - hub
      - admin
      - reader
    # command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

volumes:
  nginx_ssl:

networks:
  gaia:
    driver: bridge
    name: gaia
