version: "3.8"

services:
  prep:
    image: cmd.cat/envsubst
    restart: on-failure:10
    env_file:
      - .env
    volumes:
      - ./configs/nginx/conf.d:/configs
    networks:
      - gaia
    command: sh -c "envsubst '$${DOMAIN_NAME}' < /configs/gaia.template > /configs/gaia.conf"

  hub:
    image: blockstack/gaia-hub:2.8.2
    restart: always
    env_file:
      - .env
    volumes:
      - ./configs/gaia/hub-config.json:/src/hub/etc/config.json
      - ~/storage:/storage
    ports:
      - 3000:3000
    environment:
      CONFIG_PATH: /src/hub/etc/config.json
      GAIA_DISK_STORAGE_ROOT_DIR: /storage
      NODE_ENV: production
    networks:
      - gaia
    depends_on:
    - prep

  admin:
    image: blockstack/gaia-admin:2.8.2
    restart: always
    env_file:
      - .env
    volumes:
      - ./configs/gaia/admin-config.json:/src/admin/etc/config.json
      - ./configs/gaia/hub-config.json:/tmp/hub/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8009:8009
    environment:
      CONFIG_PATH: /src/admin/etc/config.json
      NODE_ENV: production
    networks:
      - gaia
    depends_on:
    - prep

  reader:
    image: blockstack/gaia-reader:2.8.2
    restart: always
    env_file:
      - .env
    volumes:
      - ./configs/gaia/reader-config.json:/src/reader/etc/config.json
      - ~/storage:/storage
    ports:
      - 8008:8008
    environment:
      CONFIG_PATH: /src/reader/etc/config.json
      GAIA_DISK_STORAGE_ROOT_DIR: /storage
      NODE_ENV: production
    networks:
      - gaia
    depends_on:
      - prep

  nginx:
    image: jonasal/nginx-certbot:2
    restart: always
    env_file:
      - .env
    volumes:
      - nginx_ssl:/etc/letsencrypt
      - ./configs/nginx/conf.d/gaia.conf:/etc/nginx/user_conf.d/gaia.conf
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    environment:
      CERTBOT_EMAIL: ${EMAIL}
      STAGING: 1
      DEBUG: 0
    networks:
      - gaia
    depends_on:
      - hub
      - admin
      - reader

volumes:
  nginx_ssl:

networks:
  gaia:
    driver: bridge
    name: gaia
